version: "2"
services:
#  frontend:
#    build: .
#    restart: always
#    container_name: tracker-frontend
#    expose:
#      - 80
#    ports:
#      - "80:80"
#    depends_on:
#      - backend

  backend:
    restart: always
    container_name: backend
    build: ./tracker-backend
    ports:
      - "8080:8080"
    expose:
      - 8080