version: "2"
services:
  frontend:
    build: .
    restart: always
    container_name: tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  backend:
    restart: always
    container_name: backend
    build: ./tracker-backend
    ports:
      - "8086:8086"
    expose:
      - 8086
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
